server:
  port: 8001

spring:
  application:
    name: contractor-service
  datasource:
    url: jdbc:postgresql://localhost:5311/contractordb
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
  audit:
    kafka:
      enabled: true
    file:
      enabled: true
    console:
      enabled: true

jwt:
  secret: qO8zR9Avpm1FLzXzo1kS9OytZ+QjzUpgGzkhEwo6hH4=
  issuer: fintech-application
  expiration: 3600000 # 1 час