server:
  port: 8001

spring:
  application:
    name: contractor-service
  datasource:
    url: jdbc:postgresql://localhost:5311/contractordb
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true